# Generated by Django 5.2.4 on 2025-07-27 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiry', '0004_enquiry_created_by_enquiry_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('problem_facing', models.TextField()),
                ('expected_solution', models.TextField()),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned/Initiated'), ('Solved', 'Solved'), ('Parts Required', 'Parts Required (Pending)'), ('Servicing', 'Taken for Servicing (Pending)')], default=('Created', 'Created'), max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'adviser'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_dockets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_dockets', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dockets', to='enquiry.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='DocketUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('docket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docket_update_log', to='docket.docket')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='docket',
            name='update_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='docket.docketupdatelog'),
        ),
    ]
