# Generated by Django 5.2.4 on 2025-07-27 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='docketupdatelog',
            name='assigned_engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'engineer'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_engineer', to=settings.AUTH_USER_MODEL),
        ),
    ]
