# Generated by Django 5.2.4 on 2025-07-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0002_docketupdatelog_assigned_engineer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docket',
            old_name='docket_no',
            new_name='docket_id',
        ),
        migrations.RenameField(
            model_name='docketupdatelog',
            old_name='docket_no',
            new_name='docket_id',
        ),
    ]
