# Generated by Django 5.2.4 on 2025-07-28 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0003_rename_docket_no_docket_docket_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'ADVISER'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_dockets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docket',
            name='expected_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docketupdatelog',
            name='assigned_engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'ENGINEER'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_engineer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docketupdatelog',
            name='updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'ADVISER'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_by_adviser', to=settings.AUTH_USER_MODEL),
        ),
    ]
