# Generated by Django 5.2.4 on 2025-07-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0004_alter_docket_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docket',
            old_name='contact_no',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='docket',
            old_name='whatsapp_no',
            new_name='whatsapp_number',
        ),
    ]
