# Generated by Django 5.2.4 on 2025-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0005_rename_contact_no_docket_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned/Initiated'), ('Parts Required', 'Parts Required (Pending)'), ('Servicing', 'Taken for Servicing (Pending)'), ('Solved', 'Solved')], default=('Created', 'Created'), max_length=20),
        ),
        migrations.AlterField(
            model_name='docket',
            name='whatsapp_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
