# Generated by Django 5.2.4 on 2025-07-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0006_alter_docket_status_alter_docket_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docket',
            name='update_log',
        ),
    ]
