# Generated by Django 5.2.4 on 2025-08-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0007_remove_docket_update_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='docketupdatelog',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned/Initiated'), ('Parts Required', 'Parts Required (Pending)'), ('Servicing', 'Taken for Servicing (Pending)'), ('Solved', 'Solved')], default=('Created', 'Created'), max_length=20),
        ),
    ]
