# Generated by Django 5.2.4 on 2025-08-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0008_docketupdatelog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Assigned/Initiated', 'Assigned/Initiated'), ('Parts Required (Pending)', 'Parts Required (Pending)'), ('Taken for Servicing (Pending)', 'Taken for Servicing (Pending)'), ('Solved', 'Solved')], default=('Created', 'Created'), max_length=50),
        ),
        migrations.AlterField(
            model_name='docketupdatelog',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Assigned/Initiated', 'Assigned/Initiated'), ('Parts Required (Pending)', 'Parts Required (Pending)'), ('Taken for Servicing (Pending)', 'Taken for Servicing (Pending)'), ('Solved', 'Solved')], default=('Created', 'Created'), max_length=50),
        ),
    ]
