# Generated by Django 5.2.4 on 2025-08-16 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0009_alter_docket_status_alter_docketupdatelog_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_docket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docketupdatelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
