# Generated by Django 5.2.4 on 2025-08-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0010_docket_updated_by_alter_docketupdatelog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
