# Generated by Django 5.2.4 on 2025-08-16 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0011_docket_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='docketupdatelog',
            name='updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role__in': ['ADMIN', 'ADVISER']}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_by_adviser', to=settings.AUTH_USER_MODEL),
        ),
    ]
