# Generated by Django 5.2.4 on 2025-09-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0012_alter_docketupdatelog_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docket',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='docket',
            name='last_name',
        ),
    ]
