# Generated by Django 5.2.4 on 2025-09-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0013_remove_docket_first_name_remove_docket_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='full_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
