# Generated by Django 5.2.4 on 2025-09-30 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docket', '0014_docket_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
