# Generated by Django 5.2.4 on 2025-07-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_user.png', null=True, upload_to='profile_images/'),
        ),
    ]
