# Generated by Django 5.2.4 on 2025-07-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTIONIST', 'Receptionist'), ('ADVISER', 'Adviser'), ('ENGINEER', 'Engineer')], default='ENGINEER'),
        ),
    ]
