# Generated by Django 5.2.4 on 2025-07-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecaller',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
