# Generated by Django 5.2.4 on 2025-07-23 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_telecaller_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='customer_reference_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='tele_caller_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='enquiry.telecaller'),
        ),
    ]
