# Generated by Django 5.2.4 on 2025-07-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_enquiry_created_by_enquiry_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
