# Generated by Django 5.2.4 on 2025-09-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_alter_enquiry_enquiry_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='last_name',
        ),
    ]
