# Generated by Django 5.2.4 on 2025-09-30 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_rename_first_name_enquiry_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
